sudo: false
services:
- docker
language: rust
rust:
- nightly
cache: cargo
before_script:
- git clone https://github.com/clux/posts.git
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker pull clux/muslrust
script:
- cargo test
- docker run --rm -v $PWD:/volume -w /volume -t clux/muslrust cargo build --release
- docker build -t clux/blog .
- docker run -d -p 8000:80 --name=blog -t clux/blog
- sleep 1
- curl -sSL localhost:8000 | grep "<body>"
- docker rm -f blog
after_success:
- docker push clux/blog
after_script:
- docker logout
notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    secure: QXTthzddrD9EMoIU4iPcUt3qLVUtAkkX3RhlVrQXF0IHxp1nsqlFaN7bqrl6DgD+ekFipbT46HyWw5iieXqt/GBbgeN2cUHziLzoF0noCol0OIxyA3buQCY5Dj+d0hGvka86xxRk9x+nr8oVZZ3oU5flzL8HN1YcqEtOp1aauwU=
