[package]
name = "blog"
version = "0.1.0"
authors = ["Eirik Albrigtsen <analsandblaster@gmail.com>"]

[lib]
name = "blog"
path = "src/lib.rs"

[[bin]]
name = "blog"
path = "src/main.rs"
doc = false

[dependencies]
clap = "2.2.1"
glob = "0.2.11"
hoedown = "3.0.5"
iron = "*"
router = "*"
handlebars-iron = "*"
rustc-serialize = "0.3"
logger = "*"
persistent = "0.0.6"
