[package]
name = "blog"
version = "0.1.0"
authors = ["Eirik Albrigtsen <analsandblaster@gmail.com>"]

[lib]
name = "blog"
path = "src/lib.rs"

[[bin]]
name = "blog"
path = "src/main.rs"
doc = false

[dependencies]
glob = "*"
hoedown = "*"
regex = "*"
rustc-serialize = "*"
iron = "*"
router = "*"
handlebars-iron = "*"
logger = "*"
staticfile = "*"
persistent = "*"
mount = "*"
