[package]
name = "blog"
version = "0.1.0"
authors = ["Eirik Albrigtsen <analsandblaster@gmail.com>"]

[dependencies]
clap = "2.2.1"
glob = "0.2.11"
hoedown = "3.0.5"
pencil = "0.1.2"
rustc-serialize = "0.3"
