[package]
name = "blog"
version = "0.1.0"
authors = ["Eirik Albrigtsen <analsandblaster@gmail.com>"]

[lib]
name = "blog"
path = "src/lib.rs"

[[bin]]
name = "blog"
path = "src/main.rs"
doc = false

[dependencies]
glob = "0.2.11"
hoedown = "3.0.5"
regex = "0.1"
rustc-serialize = "0.3"
iron = "*"
router = "*"
handlebars-iron = "*"
logger = "*"
staticfile = "*"
persistent = "0.1.0"
mount = "0.1.0"
